### ISSUE TITLE
Research potential reinforcement learning algorithms in Python

### ISSUE THREAD

**Issue by MohammedHaq** [MohammedHaq/MazeLearn#3]
create a document in the documentation folder "reinforcement_learning_algorithms.txt" that has information regarding what reinforcement learning algorithms can be used to solve a randomly generated maze and any positives and negatives on any methods you find.

**Comment by ahadaso042** [comment]
Hi Mohammed,

Ill have a jab at this later tomorrow.

Cheers,

Ahad

**Comment by MohammedHaq** [comment]
closing this issue. most likely using OpenAI's gym library
